name:                project-euler-fibonacci
version:             0.1.0.0
github:              "xicesky/project-euler-fibonacci"
license:             BSD3
author:              "Markus Dangl"
maintainer:          "sky@q1cc.net"
copyright:           "(c) 2021 Markus Dangl"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xicesky/project-euler-fibonacci#readme>

dependencies:
- base >= 4.7 && < 5
- data-memocombinators >= 0.5

library:
  source-dirs: src

executables:
  project-euler-fibonacci-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-euler-fibonacci

tests:
  project-euler-fibonacci-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - project-euler-fibonacci
    - QuickCheck
    - hspec
    - quickcheck-instances
